### ISSUE TITLE
Feature to provide custom error messages

### ISSUE THREAD

**Issue by basco-johnkevin** [asaskevich/govalidator#104]
Would be nice if there's a way to provide custom error messages when validating structs - https://github.com/asaskevich/govalidator#validatestruct-2

**Comment by chatwithrajaram** [comment]
I implemented custom error message by forking this code. Please take a look at my github account.
https://github.com/chatwithrajaram/govalidator

You can configure custom error message with below format.
validationTab~custom error messge

Example: required~username is manatory

If you don't specify custom error message, it will fall back to default behaviour

**Comment by waltton** [comment]
Hey @chatwithrajaram, create a PR from your fork, is more easy to review the code and all that.

**Comment by chatwithrajaram** [comment]
I created pull request. Please take a look.

On Thu, Mar 31, 2016 at 7:43 PM, Waltton Santana <notifications@github.com>
wrote:

> Hey @chatwithrajaram <https://github.com/chatwithrajaram>, create a PR
> from your fork, is more easy to review the code and all that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/asaskevich/govalidator/issues/104#issuecomment-203956910>
>



-- 
Best Regards,
Rajaram Ganjikunta

**Comment by raitucarp** [comment]
What is the status of this issue?

**Comment by asaskevich** [comment]
I hope that this issue was resolved with one of merged PRs. You can reopen issue if not.
