### ISSUE TITLE
Doesn't validate all custom validators tags

### ISSUE THREAD

**Issue by shardnit** [asaskevich/govalidator#116]
Applying multiple custom tags to a struct property only invokes the first custom validator. For example, given following scenario:

```go
func init() {
	govalidator.CustomTypeTagMap["sqlalphanum"] = govalidator.CustomTypeValidator(func(i interface{}) bool {
		switch v := i.(type) {
		case sql.NullString:
			return govalidator.IsAlphanumeric(v.String)
		}
		return false
	})
	govalidator.CustomTypeTagMap["sqlrequired"] = govalidator.CustomTypeValidator(func(i interface{}) bool {
		switch v := i.(type) {
		case sql.NullString:
			return v.Valid
		}
		return false
	})
}

type User struct {
	Name sql.NullString `valid:"sqlrequired,sqlalphanum"`
	City sql.NullString `valid:"sqlalphanum"`
}
```

`govalidator.ValidateStruct()` on user object will invoke only `sqlrequired` custom validator for `Name` property.

Looking at the source (https://github.com/asaskevich/govalidator/blob/master/validator.go#L688), it indeed returns as soon as a custom validator is found. Shouldn't it decide validity after invoking all custom validators (if more than one)?

**Comment by annismckenzie** [comment]
My bad. I'm the one who added that feature. I'll add a test and will hopefully resolve this issue. Did you by any chance implement your own fix for this and use the forked version vendored in your project? Don't want to do this work twice if that can be avoided.

**Comment by shardnit** [comment]
hey sorry for the delay in getting back on this issue. I did have a temporary fix for this but looks like you are ahead than me. Let me know if I can be of help.

**Comment by annismckenzie** [comment]
Yep, sure am – no worries. Waiting on Alex on how to proceed; as you can see, #123 introduces a BC break but applying just 13f9f0094fc734d9c446c2ba16c9dee3e0417f7d onto the current master fixes this issue without introducing a [code] BC break. If you forked and vendored the library you can also just apply the respective commit (or stay with your fix for now).

**Comment by annismckenzie** [comment]
This is now fixed – can you re-check please?

**Comment by shardnit** [comment]
👍
