### ISSUE TITLE
IsURL() return false for ascii domain names that ends with a upper-case letter 

### ISSUE THREAD

**Issue by noblehng** [asaskevich/govalidator#117]
I think the `([-\.][a-zA-Z0-9]+)*` part of the `URL` regular expression will match the TLD of a ascii domain name except for the last letter, which will be matched by the second `[a-z\x{00a1}-\x{ffff}0-9]+` instead.

So the `URL` regular expression will not match a ascii domain name that ends with a upper-case letter.

**Comment by asaskevich** [comment]
Thanks :+1:

**Comment by korovkin** [comment]
can we please also support urls that contain "_" ?

**Comment by korovkin** [comment]
this is breaking out current setup: where machines are `dev_001.service.xxx`

**Comment by korovkin** [comment]
is there a config flag to disable the check i can use for now?
