### ISSUE TITLE
Consider allowing 1-character TLDs

### ISSUE THREAD

**Issue by juliusv** [asaskevich/govalidator#125]
We started using govalidator's `IsURL()` in [Prometheus](https://github.com/prometheus/prometheus).

In https://github.com/prometheus/prometheus/issues/1579, a user reported problems with a 1-character TLD in a URL, because govalidator's URL regex assumes that TLDs need to be at least 2 characters long.

While there are no public 1-letter TLDs in existence yet, I haven't found a standard yet that says that TLDs are fundamentally limited to >=2 chars, or that 1-character TLDs may not be issued theoretically in the future.

Also, this breaks the use case where people have domain search paths and use relative URLs (where the last element doesn't need to be a valid TLD).

Would this be something that could be changed in govalidator? Otherwise if we wanted to accomodate for that use case, we'd have to use a different URL checker.

**Comment by asaskevich** [comment]
Can you provide URLs which causes wrong validation result? I'll take a look

**Comment by juliusv** [comment]
Sure. The example from https://github.com/prometheus/prometheus/issues/1579 is `http://prometheus-alertmanager.service.q:9093`, but any other example with a single-letter TLD will fail to validate.

**Comment by asaskevich** [comment]
Thanks. Is there any special cases that also unresolved in the  current `IsURL` implementation?

**Comment by asaskevich** [comment]
> https://github.com/asaskevich/govalidator/commit/5b6e9375cbf581a9008064f7216e816b568d6daa#diff-bf215ece4e5166da723b1e19a0d6b1cdR620

**Comment by juliusv** [comment]
Thanks a bunch, that should fix the 1-char TLD problem at least :)

Closing the issue.
