### ISSUE TITLE
Better documentation for ValidateStruct

### ISSUE THREAD

**Issue by vahe** [asaskevich/govalidator#128]
It'd be nice to have better docs on the ValidateStruct method. Currently there's no mention of what the result value is for. Skimming the source code I can see that it returns whether the validation was successful or not, but does it guarantee that it will be false if and only if `err != nil`?

**Comment by asaskevich** [comment]
Hi, @vahe yes, if `err != nil` result will be equal to `false`
https://github.com/asaskevich/govalidator/blob/master/validator.go#L533

**Comment by vahe** [comment]
Thanks!
