### ISSUE TITLE
can we do nested validation

### ISSUE THREAD

**Issue by wsf1991** [asaskevich/govalidator#129]
Hi, if i have a struct A, inside it there is a field that is struct B. 
type A struct {
      name string `valid:"required"`
      data   B  
}
type B struct {
     year string `valid:"required, alphanum"`
}
While we call valid.ValidateStruct(A) to validate struct A, is that also possible that it will also validate all of its fields, in this case, can we also validate struct B?

**Comment by asaskevich** [comment]
Yes, `ValidateStruct` supports nested structs: https://github.com/asaskevich/govalidator/blob/master/validator.go#L882

**Comment by annismckenzie** [comment]
This is supported and also tested in the unit tests – would close.

**Comment by asaskevich** [comment]
Alright, https://github.com/asaskevich/govalidator/blob/master/validator_test.go#L1799
