### ISSUE TITLE
Custom validator, what is the difference between having "govalidator.CustomTypeValidator"

### ISSUE THREAD

**Issue by junhsiehevo** [asaskevich/govalidator#142]
Hi There,

I am wondering what the different is between having "govalidator.CustomTypeValidator" and without it when adding a custom validator. Both ways seem to work fine. Are there any advantages/disadvantage to use one over the other? A little explanation would help. Thanks.

```
  govalidator.CustomTypeTagMap.Set("duck1", govalidator.CustomTypeValidator(func(input interface{}, context interface{}) bool {
    return input == 888
  }))
```

```
  govalidator.CustomTypeTagMap.Set("duck2", func(input interface{}, context interface{}) bool {
    return input == 888
  })
```

**Comment by asaskevich** [comment]
I think that there are no difference, first example just a wrapper 😄

**Comment by junhsiehevo** [comment]
Okay. Thanks.
