### ISSUE TITLE
IsURL() does not support IPv6 addresses

### ISSUE THREAD

**Issue by juliusv** [asaskevich/govalidator#150]
See https://github.com/prometheus/prometheus/issues/2025.

IPv6 addresses in URLs such as `http://[::1]:9093` are not recognized as valid by `IsURL()`.

**Comment by asaskevich** [comment]
Okay, I hope, it's possible to refactor regex for IsURL. There are some issues with IsURL, I'm looking for the solution

**Comment by asaskevich** [comment]
Please, check added tests, hope issue fixed:
https://github.com/asaskevich/govalidator/commit/7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877#diff-bf215ece4e5166da723b1e19a0d6b1cdR639
