### ISSUE TITLE
IsURL marks valid url starting with subdomain as invalid

### ISSUE THREAD

**Issue by jiangjin** [asaskevich/govalidator#151]
```
package main

import "github.com/asaskevich/govalidator"

func main() {
	println(govalidator.IsURL("http://m.abcd.com/test.html"))
	println(govalidator.IsURL("http://abcd.com/test.html"))
}
```

as in the example,
`http://m.abcd.com/test.html` would be marked as invalid, `http://abcd.com/test.html` is valid.

any explanation? thanks.

**Comment by asaskevich** [comment]
IsURL uses regexp that omits some valid urls, take a look at #150

**Comment by asaskevich** [comment]
Please, check added tests, hope issue fixed:
https://github.com/asaskevich/govalidator/commit/7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877#diff-bf215ece4e5166da723b1e19a0d6b1cdR639
