### ISSUE TITLE
Is there a case where err==nil but struct is not valid

### ISSUE THREAD

**Issue by gnhuy91** [asaskevich/govalidator#153]
I felt somewhat confused that `ValidateStruct()` return both `bool, error`. Is there a case where `err==nil` but struct is **invalid** and vice versa ?

Should I check for both if all I need is to verify if my struct is valid ?

**Comment by asaskevich** [comment]
No, you could check only first returned value, but if you would like to see what happened in deep, you may have a look at second `err` value.

**Comment by gnhuy91** [comment]
Thanks!
