### ISSUE TITLE
validate struct inside a map

### ISSUE THREAD

**Issue by daseinhorn** [asaskevich/govalidator#156]
Hi all

I'm using govalidator to validate the incoming data for my REST backend.
Due to the special nature of this data I use an array (slice) inside of the main struct.

If I validate the data with govalidator.ValidateStruct(incomingData) everything works fine except for the validation of the data inside the mentioned slice. The workaround for me is to create a for loop and call govalidator.ValidateStruct(childItem) for every item that is inside the slice.

I created a [playground](https://play.golang.org/p/1kKj5lRHXw) so you can get a better understanding of what I'm talking about.

Is there a better solution for this?

**Comment by nejcpenko** [comment]
Hi @daseinhorn,

Have you tried adding valid:"required" to the Struct field? 

```go
type MainStruct struct {
	Content []ChildStruct `json:"content" valid:"required"`
}
```

**Comment by asaskevich** [comment]
Yes, it seems to be solved with `valid: "required"` tag.
