### ISSUE TITLE
"valid" need to be first parameter?

### ISSUE THREAD

**Issue by avelino** [asaskevich/govalidator#159]
When does not put the "valid" as the first parameter in the struct it does not work.

**Comment by Tang-RoseChild** [comment]
it use this func [func (StructTag) Get](https://golang.org/pkg/reflect/#StructTag.Getl) to get field tag.
well there maybe a mistake in the official golang source code:
Get will call func Lookup to find tag name. In Lookup, after found a tag name, it will check whether is the given. if not,it will find the next tag name  using rest string,then the delimiter of the tag name will be the first character of next field key name. For example:
```
type demo struct {
  Name string `json:"name",valid:"stringlength(2|10)"
}
```
first tag name will be "json",and the second tag name will be ",valid",not "valid",so it does not work

**Comment by wilsontamarozzi** [comment]
I'm sorry for my english.

In my project it works normally.
https://github.com/wilsontamarozzi/panda-api/blob/master/services/models/people.go#L20

When placing a tag, you can not use the TAB to indent, the tags should only contain one space between the others.

**Comment by colindickson** [comment]
i think what avelino means is that if "valid" is not the first struct tag, then govalidator doesn't work properly.  example:

```
type Foo struct {
	Email string `json: "email" valid:"email"`
}

func main() {
	fmt.Println(govalidator.ValidateStruct(&Foo{"not_an_email"}))
}
```
this outputs:
true <nil>
which is incorrect
but if you fix the ordering of the struct tags to make "valid" first:

```
type Foo struct {
	Email string `valid:"email" json: "email"`
}

func main() {
	fmt.Println(govalidator.ValidateStruct(&Foo{"not_an_email"}))
}
```

then this will give the expected result: 
false Email: derp does not validate as email;

**Comment by emirhanmarlali** [comment]
@colindickson i think the problem is the space between `json:` and `"email"`

in this example json tag also won't work
```golang
type Foo struct {
	Email string `json: "email" valid:"email"`
}

func main() {
	foo := &Foo{"not_an_email"}
	fmt.Println(govalidator.ValidateStruct(foo)) // prints => true <nil>

	body, _ := json.Marshal(foo)
	fmt.Println(string(body)) // prints => {"Email":"not_an_email"}
}
```

Json marshaller will use exposed attribute name `Email` 

The syntax is incorrect so remaining  tags won't be processed.

But in this example; 
```golang
type Foo struct {
	Email string `valid:"email" json: "email"`
}

func main() {
	foo := &Foo{"not_an_email"}
	fmt.Println(govalidator.ValidateStruct(foo)) // prints => false Email: not_an_email does not validate as email;

	body, _ := json.Marshal(foo)
	fmt.Println(string(body)) // prints => {"Email":"not_an_email"}
}
```
First tag is processed then syntax error appears. So validation tag works correctly but json marshaller will use exposed attribute name `Email`.

Correct example 1:
```golang
type Foo struct {
	Email string `valid:"email" json:"email"`
}

func main() {
	foo := &Foo{"not_an_email"}
	fmt.Println(govalidator.ValidateStruct(foo)) // prints => false email: not_an_email does not validate as email;

	body, _ := json.Marshal(foo)
	fmt.Println(string(body)) // prints => {"email":"not_an_email"}
}
```
Correct example 2:
```golang
type Foo struct {
	Email string `json:"email" valid:"email" `
}

func main() {
	foo := &Foo{"not_an_email"}
	fmt.Println(govalidator.ValidateStruct(foo)) // prints => false email: not_an_email does not validate as email;

	body, _ := json.Marshal(foo)
	fmt.Println(string(body)) // prints => {"email":"not_an_email"}
}
```

**Comment by asaskevich** [comment]
Already resolved, thanks to everybody.

**Comment by avelino** [comment]
@asaskevich what does the solution commit? I'd like to understand the error

**Comment by asaskevich** [comment]
Can't find solution commit but there is the line responsible for it: https://github.com/asaskevich/govalidator/blob/6c3cb3214c0bf1206da40f9cb4eef372a5788307/validator.go#L904
Maybe an issue was in https://golang.org/pkg/reflect/#StructTag.Get function that splits the string by space.
