### ISSUE TITLE
IsFilePath returns false for valid unix file paths

### ISSUE THREAD

**Issue by favadi** [asaskevich/govalidator#161]
In this PR: https://github.com/asaskevich/govalidator/pull/160, I added some valid unix file paths, but IsFilePath return fase.

**Comment by favadi** [comment]
It is either I misunderstand the purple of IsFilePath, or it is completely broken.

**Comment by favadi** [comment]
I don't understand the regex at: https://github.com/asaskevich/govalidator/blob/7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877/patterns.go#L44, because AFAIK, almost everything except '/' is accepted for unix file name.

**Comment by Gnouc** [comment]
@favadi 
> because AFAIK, almost everything except '/' is accepted for unix file name.

everything except `NUL` byte and `/` is accepted as unix file name.

For this one, it's unix path, so everything except `NUL` byte is ok.
