### ISSUE TITLE
Add valid rune length

### ISSUE THREAD

**Issue by Tang-RoseChild** [asaskevich/govalidator#162]
hi,guys

there is one case : need to valid Chinese (or other language) text's rune length ,for example:
"你"‘s string length is 3,but rune length is 1.And we want to valid rune length.

Can we add one more rune length validator, similar to string length validator,  like :
type demo struct {
  Name string `valid:"runelength(2|4)"`
}

**Comment by asaskevich** [comment]
You can use `stringlength` which works as you expect
```
type demo struct {
   Name string valid:"stringlength(2|4)"
}
```
