### ISSUE TITLE
IsURL checks bytes length instead of characters

### ISSUE THREAD

**Issue by dmbreaker** [asaskevich/govalidator#166]
IsURL contains code: len(str) >= 2083
Number 2083 comes from IE URL limitation, but there mentioned characters, not bytes.
Moreover, in validator.js url.length >= 2083 relates to characters count, not bytes.
I think this check should be replaced by utf8.RuneCountInString(str) >= 2083

**Comment by alioygur** [comment]
bytes count always greater than runes so there is no problem :)
