### ISSUE TITLE
isValidTag check is not correct for regexp

### ISSUE THREAD

**Issue by denouche** [asaskevich/govalidator#170]
Hello,

I'm trying to apply a custom regexp on a field, something like:
```
type ParamsHook struct {
	Name string `json:"name" valid:"required,matches(^\\$[A-Za-z]$)"`
}
```

But because of the `isValidTag` check, my regexp appears as invalid.
The code of the function in `validator.go` is:
```
switch {
case strings.ContainsRune("!#$%&()*+-./:<=>?@[]^_{|}~ ", c):
	// Backslash and quote chars are reserved, but
	// otherwise any punctuation chars are allowed
	// in a tag name.
default:
	if !unicode.IsLetter(c) && !unicode.IsDigit(c) {
		return false
	}
}
```

Why backslash are not allowed in tags ?

How to achieve what I want to do?

Thank you

**Comment by jack-chung** [comment]
This fix has since disappeared from the code (overwritten by a later merge). Can you please put it back?

**Comment by denouche** [comment]
https://github.com/asaskevich/govalidator/pull/205
