### ISSUE TITLE
Feature Request: Travers into pointers in govalidator.ValidateStruct() 

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [asaskevich/govalidator#180]
Would you be willing to traverse into pointers in govalidator.ValidateStruct(), as we use nested structures it would be much more convenient to do that directly from the package.

I am willing to provide a pr if you are up for it.

**Comment by asaskevich** [comment]
Now it works with pointers and nested structs, isn't it? If not, reopen this issue with an example that shows expected behaviour, please.

**Comment by morriswinkler-simplesurance** [comment]
Cool @asaskevich, could you point me to the commit that introduced that.

**Comment by asaskevich** [comment]
It is somewhere here: https://github.com/asaskevich/govalidator/blob/master/validator.go#L1087

**Comment by morriswinkler-simplesurance** [comment]
Thanks
