### ISSUE TITLE
Capital Letter for the first letter in struct property?

### ISSUE THREAD

**Issue by tokidoki11** [asaskevich/govalidator#187]
Hi, I have some issue for struct validation on the struct below
```
type myStruct struct {
	id                 string  `valid:"required,uuidv4"`
}
```
The validation will always return true for the "id" because of skipping the validation

After I change the "id" to "ID" or "Id" the validation will run successfully
```
type myStruct struct {
	ID                  string  `valid:"required,uuidv4"`
}

```

**Comment by umarniz** [comment]
Golang does not export variables that are not capital, this means this variable will not be viewable outside of the package.

I am assuming this will cause the govalidator not be able to see it too as it works via reflection and the variables beginning with small letters aren't exported for reflection either.

**Comment by tokidoki11** [comment]
Thanks, didnt know that 😅
