### ISSUE TITLE
DNS validation doesn't allow label with 1 character

### ISSUE THREAD

**Issue by karthik-uci** [asaskevich/govalidator#198]
This is a valid domain name, 
ru.link.n.svpncloud.com

Regex needs to be fixed to `^([a-zA-Z0-9]{1}[a-zA-Z0-9_-]{0,62}){1}(\.[a-zA-Z0-9]{1}[a-zA-Z0-9_-]{0,62})*$`

**Comment by mistabubbles** [comment]
+1

It also not works with domain `r.fullstory.com`
