### ISSUE TITLE
setting required on time.Time{} (zero value of time) gives non zero value required

### ISSUE THREAD

**Issue by amankapoor** [asaskevich/govalidator#246]
Hi,

I ran into three problems today. First was with bool being false, I read your comments in other issues and instead of doing *bool, I removed the valid tag from bool keys.

The second I am facing right now is with zero value of time. If I set a key to have zero value then I get `non zero value required`. What are my options here? Remove the valid tag?

Third is that any int set to 0 also gives non zero value required. This I can manage in my code by changing the const iota to start from 1.

But, the word require indicates that the value should be there, now Go works differently and has zero values and I haven't read your implementation yet. But, is there any way so that my validator function starts understanding that even if a bool is false. time is zero or int is zero, validate them?

Please let me know what can be done. I don't want to remove more valid tags just to get things work.

**Comment by asaskevich** [comment]
Thank you for your investigation, it seems to be fixed in #329.
Sorry for long awaited response.
