### ISSUE TITLE
Go 1.10 beta changes to net/uri break irc://#channel@network URI validation

### ISSUE THREAD

**Issue by logic** [asaskevich/govalidator#250]
Just a quick head's-up: Go 1.10 [introduces changes to `net/url`](https://tip.golang.org/doc/go1.10#net/url) which appear to break the unit tests for `irc://#channel@network` URIs on `IsRequestURL` and `IsRequestURI`.

Changing to `irc:///` (three slashes, to formally omit `hostname:port`) works properly for those two tests (on both Go 1.9 and 1.10), but fails on `IsURL` (on both; the two-slash variant validates fine on both 1.9 and 1.10).

I haven't had a chance to dig into this beyond a quick "oh, my builds are failing, wonder what happened", but thought I'd pass this along sooner rather than later.

**Comment by stapelberg** [comment]
Specifically, this is upstream commit https://github.com/golang/go/commit/ba1018b4549f3edc257221cc8e49221255e03290#diff-9667474d33400190658e4758cf28dbf5

**Comment by stapelberg** [comment]
And this issue was discussed upstream at https://github.com/golang/go/issues/23657
