### ISSUE TITLE
How to validated boolean value?

### ISSUE THREAD

**Issue by shivkumarsingh7** [asaskevich/govalidator#256]
_type Request struct {
Active bool `json:"active" valid:"required~Status should not be blank"`
}_

When active variable have value "false" its always invalidate.

**Comment by jmunson** [comment]
A bool is either true or false, so I'm not sure "required" is really something you want to check for since it does not really make sense in that context.

You might want a pointer to a bool, which could then be nil, true, or false.  Or something like a sql.NullBool which behaves similarly.

**Comment by shivkumarsingh7** [comment]
Yes, @jmunson , But when we are taking input from users, validation should be there. What if user not passing any value to bool parameter.

**Comment by jmunson** [comment]
If you're storing it in a bool, then it will be zero.  Let me demonstrate the issue I'm talking about with a table comparing how this would be stored in a bool, or in a pointer to a bool.

|user action|bool value|*bool value|
|-------------|-----------|-------------|
|submits true value|1|1
|submits false value|0|0|
|submits no value|0|nil|

As long as you're trying to represent this in a bool, its impossible to tell the difference between someone submitting false, and someone not submitting anything.

With your variable being a pointer to a bool, it defaults to nil, which means its not pointing to a valid bool.  Then you can validate that such that the pointer must point to a valid bool and you'll know it exists.

This is similar to how sql.NullBool works.  Databases have this same issue where they need to differentiate between true, false, and not existing.

A [sql.NullBool](https://godoc.org/database/sql#NullBool) is a small struct containing a bool, and then a "Valid" bool to keep track of whether this NullBool.Bool has been set. With a NullBool, someone not supplying input would produce a sql.NullBool{Bool: 0, Valid:0}  where someone supplying a false valid would produce sql.Nullbool{Bool 0, Valid: 1}

**Comment by AlexAslan** [comment]
Hello @jmunson. We have a similar case with a struct that contains a *bool where we try to json decode the body of an http request, but it seems that the ValidateStruct does not the data provided for that field properly. If we mark the attribute as required, then 

Sample code we used:
`      decoder := json.NewDecoder(request.Body)
	if err = decoder.Decode(&mySctruct); err != nil {
		fmt.Println(err)
	}
       fmt.Println("MY_CUSTOM_BOOL: ", myStruct.myBool) // this prints <nil> as it should if in json "my_bool": null. But it fails the validation if "my_bool" is true || false

	if ok, err := govalidator.ValidateStruct(myStruct); err != nil {
		validationError := map[string]interface{}{"validationError": err}
		json.NewEncoder(writer).Encode(validationError)
		return
	} else {
		fmt.Printf("OK: %v\n", ok)
	}`

Do you have any suggestions? Are we doing something wrong here?

**Comment by dulumao** [comment]
govalidator.TagMap["boolean"] = govalidator.Validator(func(str string) bool {
		boolMap := map[string]bool{
			// true
			"1":    true,
			"true": true,
			"on":   true,
			"yes":  true,
			// false
			"":      false,
			"0":     false,
			"false": false,
			"off":   false,
			"no":    false,
		}

		if state, ok := boolMap[strings.ToLower(str)]; ok {
			return state
		}

		return false
	})

**Comment by dulumao** [comment]
`govalidator.TagMap["boolean"] = govalidator.Validator(func(str string) bool {
		boolMap := map[string]bool{
			// true
			"1":    true,
			"true": true,
			"on":   true,
			"yes":  true,
			// false
			"":      false,
			"0":     false,
			"false": false,
			"off":   false,
			"no":    false,
		}

		if state, ok := boolMap[strings.ToLower(str)]; ok {
			return state
		}

		return false
	})`

**Comment by dulumao** [comment]
govalidator.TagMap["boolean"] = govalidator.Validator(func(str string) bool {
		boolMap := map[string]bool{
			// true
			"1":    true,
			"true": true,
			"on":   true,
			"yes":  true,
			// false
			"":      false,
			"0":     false,
			"false": false,
			"off":   false,
			"no":    false,
		}

		if state, ok := boolMap[strings.ToLower(str)]; ok {
			return state
		}

		return false
	})

**Comment by bitsofinfo** [comment]
I have the same issue, user input, its boolean, but not sure how to detect not present.

**Comment by rezaghanbari** [comment]
@dulumao I think It's better to change this part:
`if _, ok := boolMap[strings.ToLower(str)]; ok {
			return true
		}`

**Comment by asaskevich** [comment]
Thank you for your investigation, it seems to be fixed in #329.
Sorry for long awaited response.
