### ISSUE TITLE
question: Why the IsInt("") return true

### ISSUE THREAD

**Issue by zhaoyeuchao** [asaskevich/govalidator#258]
Hi
I am a novice in the Golang.
I have a problem with IsInt(). If I define "var a string" and use IsInt(a), then I will get a result is true. But the "a" is not an integer in my opinion.
I can't understand. So, I want need you help.
Thank you

**Comment by jasonlam604** [comment]
Yes, that is expected behavior empty string is considered 0

**Comment by zhaoyeuchao** [comment]
Thank you for your help！
It seems that this is a feature of the Golang.
So，I understood. Now, I don’t want to get true with IsInt(a) when the a is empty, I can decide the “a” is not empty string first.
Thank you very much.
I  close this issue.
