### ISSUE TITLE
Email validation requires internet access.

### ISSUE THREAD

**Issue by asyndrige** [asaskevich/govalidator#266]
What if my application works only in intranet or does not have internet access at all? I can just use previous version and be ok with it, but I think this is totally wrong. Need to check internet access before host lookup or provide boolean flag to function, if it can do it.
https://github.com/asaskevich/govalidator/blob/ccb8e960c48f04d6935e72476ae4a51028f9e22f/validator.go#L75

**Comment by asaskevich** [comment]
https://github.com/asaskevich/govalidator/commit/7d2e70ef918f16bd6455529af38304d6d025c952#diff-2c21fb78980d1744f15f8637f5c8700bR55

**Comment by joshlreese** [comment]
Would it be possible to get a v10 tag for this, considering it's been some time since a release?
