### ISSUE TITLE
Validator won't attempt to validate an empty slice

### ISSUE THREAD

**Issue by kuberlog** [asaskevich/govalidator#276]
```
func IsNonEmptyIntArray(arrInterface interface{}, context interface{}) bool {
	defer G(O())
	if arr, ok := arrInterface.([]int); ok && len(arr)>0{
		fmt.Println("LenArr:")
		fmt.Println(len(arr))
		return true
	}
	return false
}

```
This fn is set as a custom tag and it will not even run if the slice is empty. Validate will return an OK even if the slice is empty because this function won't run.

**Comment by SlightlyCyborg** [comment]
https://github.com/asaskevich/govalidator/blob/7d2e70ef918f16bd6455529af38304d6d025c952/validator.go#L708 

this seems to be the problem. However, my slice I think is a nil slice, not an empty slice, so I will explicitly use make to generate the slice so it validates properly.

**Comment by SlightlyCyborg** [comment]
Nope, making the slice an empty slice didn't work....so IDK.

**Comment by SlightlyCyborg** [comment]
It seems that the recursive call to Interface() ends up turning the empty slice into a nil slice.

**Comment by balaji39mit** [comment]
@SlightlyCyborg : Assume you are having some structs which has required fields, but the struct is nil. In this case, whether the ValidateStruct is returning true? It would be much helpful when you post the issue with an example. TIA.

**Comment by ivanjaros** [comment]
I needed a []string to be non-empty and setting it to "required" worked.
