### ISSUE TITLE
add validate file path function

### ISSUE THREAD

**Issue by oryband** [asaskevich/govalidator#28]
- should validate if string is a valid file path
- should differ between OSes e.g. `/home/me/file.txt` is valid in unix based OSes.
- anything else I haven't thought of

**Comment by oryband** [comment]
waiting excitedly for an update :)

**Comment by asaskevich** [comment]
@oryband, I hope that it already ready to use: https://github.com/asaskevich/govalidator/commit/29b13e16b483f7731146f9f5e16c8ed1772ba26f
