### ISSUE TITLE
the method ValidateStruct called tiwce when the field is Struct

### ISSUE THREAD

**Issue by tangxiaodon89** [asaskevich/govalidator#291]
this is one please call the ValidateStruct
		if (valueField.Kind() == reflect.Struct ||
			(valueField.Kind() == reflect.Ptr && valueField.Elem().Kind() == reflect.Struct)) &&
			typeField.Tag.Get(tagName) != "-" {
			var err error
			structResult, err = ValidateStruct(valueField.Interface())
			if err != nil {
				errs = append(errs, err)
			}
		}

and then this called typeCheck method
		resultField, err2 := typeCheck(valueField, typeField, val, nil)
in the typeCheck mtehod called the ValidateStruct one more time
	case reflect.Struct:
		return ValidateStruct(v.Interface())

i get the validate error info like this.
memory must not be null.;memory must not be null.;

**Comment by asaskevich** [comment]
Thank you for your investigation, it seems to be fixed in #330
