### ISSUE TITLE
isURL not working?

### ISSUE THREAD

**Issue by jbreitbart** [asaskevich/govalidator#30]
I am not sure if I am doing this the right way, but

println(govalidator.IsURL(`http://user@pass:domain.com/path/page`))

return false for me. Shouldn't this be true? Furthermore, I get the following results:

println(govalidator.IsURL(`http://www.domain.com`)) returns true
println(govalidator.IsURL(`http://blog.domain.com`)) returns false

**Comment by jbreitbart** [comment]
IsRequestURL works as expected, thanks. I still find IsURL confusing

**Comment by asaskevich** [comment]
Maybe `IsURL` can be replaced with `IsRequestURL` if they have similar behaviour?
