### ISSUE TITLE
IsUTFDigit accepting some Strings it (IMO) shouldn't

### ISSUE THREAD

**Issue by Dadie** [asaskevich/govalidator#33]
The IsUTFDigit accepts strings which contains non valid Digit character or aren't even valid numbers. 

IsUTFDigit accepts:
"-1"
"1-1"
"-"
"--------1"
"1---"
IsUTFDigits rejects:
"+1"
"1+1"
"+"
"+++++++1"
"1+++"

The question here is, what is the intended reaction of the IsUTFDigit function.

**Comment by asaskevich** [comment]
I wrote to the author of these functions (Pull Request #21)

**Comment by Dadie** [comment]
Thank you. It seems also that every *Is*-Function that works on numbers allows "-" but not "+". Like *IsFloat("+1.0")* return **FALSE** while *IsFloat("1.0")* and *IsFloat("-1.0")* returns **TRUE**. Same behavior can be found in *IsFloat*, *IsInt*, *IsUTFNumeric*, *IsAlphanumeric* and *IsNumeric*.

**Comment by asaskevich** [comment]
Thanks again :+1: , it's also mistake on regexps from parent project, I opened new issue here https://github.com/chriso/validator.js/issues/346

**Comment by asaskevich** [comment]
Thank you. It seems also that every Is-Function that works on numbers allows "-" but not "+". 
    Like IsFloat("+1.0") returns FALSE while IsFloat("1.0") and IsFloat("-1.0") return TRUE. 
    Same behavior can be found in IsFloat, IsInt, IsUTFNumeric, IsAlphanumeric and IsNumeric.

Fixed :smile:

**Comment by Dadie** [comment]
First of all, thanks ^^ *IsInt* and *IsFloat* seems to work now just fine. *IsInt("+1")* returns **TRUE** as does *IsFloat("+1.0")*. 

But now *IsNumeric("+1")* returns **TRUE** while *IsAlphanumeric("+1")*, *IsUTFNumeric("+1")* and *IsUTFDigit("+1")* return **FALSE**

The question is, should every function here return **TRUE** on "+1" and "-1" or should only *IsFloat* and  *IsInt* return **TRUE** (as '+' and '-' isn't a digit, alpha or numeric character).

**Comment by asaskevich** [comment]
If these functions returns true on '-1', I think, that they should return similar answer on '+1'. Plus sign has similar sense as minus sign, IMO. So, if any function works with numbers and returns 'true' in cases with minus sign,  they should return 'true' also in case with plus sign. I made this behaviour just for 'IsInt, IsNumeric and IsFloat', so I agree with you and these functions should be fixed.

**Comment by slugmobile** [comment]
Just submitted a pull request correcting the behaviour of UTFDigit and UTFNumeric. Both return true only for -1, 1, +1.

**Comment by asaskevich** [comment]
I hope that I can close this issue.
