### ISSUE TITLE
Empty string on some functions TRUE on some FALSE

### ISSUE THREAD

**Issue by Dadie** [asaskevich/govalidator#34]
On some functions empty string is valid and returns **TRUE** on others it is not and returns **FALSE**.

First of all empty string returns **FALSE** on *IsASCII(str string)**. 
On *IsAlpha(str string)* empty string returns **FALSE**, but on *IsUTFLetter(str string)* it returns **TRUE**

*IsAlphanumeric("")* returns **FALSE**
*IsUTFLetterNumeric("")* returns **TRUE**
*IsNumeric("")* returns **FALSE**
*IsUTFNumeric("")* returns **TRUE**
*IsUTFDigit("")* returns **TRUE**

*IsLowerCase("")* returns **TRUE**
*IsUpperCase("")* returns **TRUE**
*IsFullWidth("")* returns **FALSE**
*IsHalfWidth("")* returns **FALSE**
*IsVariableWidth("")* returns **FALSE**

As of my own opinion every character in empty string is a valid Alphanumeric, Numeric, UTFNumeric, UTFDigit, UpperCase, LowerCase, FullWidth, HalfWidth, VariableWidth, Alpha and UTFLetter character, as there is no character in empty string.

So shouldn't these functions all return **TRUE** on empty string?

**Comment by asaskevich** [comment]
I'm agree, plus sign must be replaced with asterisk, e.g. here:
https://github.com/asaskevich/govalidator/blob/master/patterns.go#L15-L17.
I open same issue on the repository of validator.js, because it has same problem: https://github.com/chriso/validator.js/issues/345

**Comment by asaskevich** [comment]
Please, check it. I hope that this issue fixed.

**Comment by Dadie** [comment]
Thanks, works now just fine, can be closed (IMO)
