### ISSUE TITLE
Breaking change: `required` no longer validates zero value strings

### ISSUE THREAD

**Issue by bmhatfield** [asaskevich/govalidator#359]
I have a simple struct, like:

```go
type SpannerSlugger struct {
	Slug string `spanner:"slug" valid:"required"`
	Name string `spanner:"name" valid:"required"`
}
```

and a test like

```ok
func TestValidation_Slugs(t *testing.T) {
	ok, err := govalidator.ValidateStruct(&db.SpannerSlugger{})
	assert.OK(t, err)
	assert.True(t, ok, "expected ok")
}
```

On SHA `f61b66f89f4a`, this works as expected (the empty string values result in the test failing)

```
% cat go.mod | grep govalidator
	github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
```

On SHA `475eaeb16496`, it fails silently (the test passes without the expected error)

```
cat go.mod | grep govalidator
	github.com/asaskevich/govalidator v0.0.0-20200108200545-475eaeb16496
```

This seems like a pretty significant regression / change, as validation that I expect to be performed is no longer being performed.

**Comment by bmhatfield** [comment]
I just spent some time trying out different commit SHAs, and it appears that this commit is what introduced this breakage: https://github.com/asaskevich/govalidator/commit/2abf7b9d5da33ab5e25960c301ca26f779a88db9

The switch from `isEmptyValue` to `isFieldSet` coupled with the corresponding test changes seems suspicious.

cc @asaskevich

**Comment by asaskevich** [comment]
@bmhatfield Thank you, investigating for the solution

**Comment by kolaente** [comment]
I am also hitting this, is there any update?

**Comment by fabianem** [comment]
Any news regarding this issue? 
Experiencing the same problem on commit [21a406dcc535](https://github.com/asaskevich/govalidator/commit/21a406dcc535d9c8a8fcc1a3b7f51b2718c30065)

**Comment by BahmanBinary** [comment]
I have this problem too 
![giphy](https://user-images.githubusercontent.com/43523245/88070284-c2f3c300-cb87-11ea-8206-1bca4bfbe722.gif)

**Comment by kolaente** [comment]
@asaskevich Anything new? This is clearly a breaking change. It prevents me from updating govalidator.

**Comment by ozburo** [comment]
I go through all the Govalidators, I find this one, "looks nice" I say to myself, read the docs, install it, refactor my code to make use of it, and it fails to deliver on the simplest of things it was supposed to do.

You had one job.

**Comment by bmhatfield** [comment]
Bump? Based upon the responses here, it seems like the [breaking commit author's understanding is incomplete](https://github.com/asaskevich/govalidator/pull/329) and perhaps 329 should be reverted?

**Comment by bmhatfield** [comment]
It appears this issue may have been resolved: https://github.com/asaskevich/govalidator/commit/63eac4636d06ec91ef7f8290e2e021912e610051

**Comment by sergeyglazyrindev** [comment]
Hello guys!
I forked this package cause owner disappeared. Hope, he will be back, but it would be easier to merge these changes back if he is back
Link to my repo: create issue there and we'll discuss it.
