### ISSUE TITLE
null tag: support integers

### ISSUE THREAD

**Issue by hazcod** [asaskevich/govalidator#376]
Hi, for my API endpoint I need to make sure that people do not try to use their own primary keys.
This is done via:
```go
type Custom struct {
	Id			uint32		`pg:"id,pk" json:"id" validate:"null"`
}
```

But this still goes through if I post with `{"id":1}`

**Comment by msiner** [comment]
The tag name is incorrect. Instead of "validate" it needs to be "valid". I believe the example below shows the behavior you are expecting.
```go
type Custom struct {
	Id uint32 `pg:"id,pk" json:"id" valid:"null"`
}

func main() {
	x := Custom{Id: 1}
	ok, err := govalidator.ValidateStruct(x)
	fmt.Println(ok, err)
	y := Custom{}
	ok, err = govalidator.ValidateStruct(y)
	fmt.Println(ok, err)
}
```
Output:
```
false id: 1 does not validate as null
true <nil>
```
