### ISSUE TITLE
tests fail on TestIsExistingEmail

### ISSUE THREAD

**Issue by wangsongc** [asaskevich/govalidator#391]
log:
=== CONT  TestIsExistingEmail
      validator_test.go:661: Expected IsExistingEmail("nosuchdomain@bar.coffee") to be false, got true.
--- FAIL: TestIsExistingEmail (0.45s)
 

I have different opinions on the result of IsExistingEmail("nosuchdomain@bar.coffee"), I think the result should be True, not false.

**Comment by prasunjoshi** [comment]
this can be closed now @wangsongc
