### ISSUE TITLE
Weird URL Validation

### ISSUE THREAD

**Issue by edoardottt** [asaskevich/govalidator#398]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 11

#### Summary

Maybe i didn't understood well the docs, but I think I encountered a weird thing.

#### Current behavior

On validate the URL `100.55.44.36ewretyt4r3wewd3`, the method govalidator.IsURL() returns true

#### How to reproduce

```
package main

import (
	"fmt"
	"github.com/asaskevich/govalidator"
)

func main() {
	validURL := govalidator.IsURL("100.55.44.36ewretyt4r3wewd3")
	fmt.Println(validURL)
}
```

#### Expected behavior
The code (I think) should print `false`

**Comment by blacklat** [comment]
```
import "net/url"
...
func IsURL(str string) bool {
    u, err := url.Parse(str)
    return err == nil && u.Scheme != "" && u.Host != ""
}
```

**Comment by edoardottt** [comment]
Did you try it?
This code prints true, false, false
```
package main

import (
	"net/url"
	"fmt"
)

func main() {
    str := "100.55.44.36ewretyt4r3wewd3"
    u, err := url.Parse(str)
    fmt.Println(err == nil)
    fmt.Println(u.Scheme != "")
    fmt.Println(u.Host != "")
}
```

**Comment by edoardottt** [comment]
Ok. Then I've understood ahah. That was only a URL validator, there are also Ipv4 and Ipv6 validators. Clearly `100.55.44.36ewretyt4r3wewd3` is a valid URL, but it isn't a valid Ip.
