### ISSUE TITLE
lessEqual(value), moreEqual(value), equal(value), notEqual(value) Options on structs

### ISSUE THREAD

**Issue by Dadie** [asaskevich/govalidator#41]
Currently there are validator functions like `IsInt`, but sometime it could be even more helpful to restrict the values further with  a _min_  or/and a _max_ value. I'd really like to extend.the functionality so that such checks could be done. 

But as of now, I'm not that sure which approach would be the best, therefor I'd like to hear everyones opinion first. I'm open for other ideas or other approaches! This "issue" should be about how to solves this "feature request" the best!

As my idea goes I would like to introduce 4 new options: `lessequal(value)`, `moreequal(value)`, `equal(value)`, `notequal(value)`. I chose those options as every "validator" is in conjunction with each other. Therefor we can't say `less(value)` and `equal(value)` to get `lessequal(value)`, because if "a < b" is true "a = b" can't be true, therefore the validation would always return false.

the usage would then look like this
```go
type Foobar struct {
    number1 string `valid:"int,lessequal(5),moreequal(-10),notequal(0)"` //means -10 <= number1 <= 5 && number1 != 0
    cons6 string `valid:"int,equal(6)"` //means cons6 == 6
    number2 string `valid:"int,lessequal(5),notequal(5)"` //means number2 < 5
    name string `valid:"ascii,noequal(admin)"` //means every (ascii) name beside 'admin' is valid
    uuid string `valid:"uuid, moreequal(A0000000-0000-0000-0000-000000000000)"`
}
```

we could even add some more options like `range(min,max)`, but at first I'd like to concentrate on the 
4 options I mentioned. If this 4 are done right, adding more should be quite easy (especially options like `range(min,max)`)

Now about how my current approach would look like respectively how I would implement this:

First of all I would define a basic Validator struct which would be more or less the foundation of most (maybe all) validators.

```go
//Basic Validator
type basicValidatorType struct {
	less  func(v1, v2 interface{}) bool
	more  func(v1, v2 interface{}) bool
	equal func(v1, v2 interface{}) bool
}

func (b basicValidatorType) isLessEqual(value, referenceValue string) bool {
	v, errV := b.convert(value)
	r, errR := b.convert(referenceValue)
	if errV != nil || errR != nil {
		return false
	}
	if b.equal != nil && b.equal(v, r) {
		return true
	}
	if b.equal == nil && reflect.DeepEqual(v, r) {
		return true
	}
	if b.less != nil && b.less(v, r) {
		return true
	}
	return false
}
func (b basicValidatorType) isMoreEqual(value, referenceValue string) bool {
	v, errV := b.convert(value)
	r, errR := b.convert(referenceValue)
	if errV != nil || errR != nil {
		return false
	}
	if b.equal != nil && b.equal(v, r) {
		return true
	}
	if b.equal == nil && reflect.DeepEqual(v, r) {
		return true
	}
	if b.more != nil && b.more(v, r) {
		return true
	}
	return false
}
func (b basicValidatorType) isEqual(value, referenceValue string) bool {
	v, errV := b.convert(value)
	r, errR := b.convert(referenceValue)
	if errV != nil || errR != nil {
		return false
	}
	if b.equal == nil {
		return reflect.DeepEqual(v, r)
	}
	return b.equal(v, r)
}
func (b basicValidatorType) isNotEqual(value, referenceValue string) bool {
	v, errV := b.convert(value)
	r, errR := b.convert(referenceValue)
	if errV != nil || errR != nil {
		return false
	}
	if b.equal == nil {
		return !reflect.DeepEqual(v, r)
	}
	return !b.equal(v, r)
}
func (b basicValidatorType) convert(value string) (interface{}, error) {
	return value, nil
}
```

The validators then would look like this (here an example of how `IsInt` would look like)

```go
//ValidatorType for IsInt
type validatorInt basicValidatorType

func (v validatorInt) convert(value string) (interface{}, error) {
	valueInt, err := strconv.ParseInt(value, 10, 64)
	return valueInt, err
}

var intValidator = validatorInt{
    //less
	func(v1, v2 interface{}) bool {
		int1, ok1 := v1.(int64)
		int2, ok2 := v2.(int64)
		if ok1 != true || ok2 != true {
			return false
		}
		return int1 < int2
	},
    //more
	func(v1, v2 interface{}) bool {
		int1, ok1 := v1.(int64)
		int2, ok2 := v2.(int64)
		if ok1 != true || ok2 != true {
			return false
		}
		return int1 > int2
	},
    //equal
	func(v1, v2 interface{}) bool {
		int1, ok1 := v1.(int64)
		int2, ok2 := v2.(int64)
		if ok1 != true || ok2 != true {
			return false
		}
		return int1 == int2
	},
}

func IsInt(str string) bool {
	_, err := intValidator.convert(str)
	return err == nil
}
```

To do all this I would need (IMO) to rebuild the whole validation process as shown in my example of `IsInt`. Rebuilden the whole code is something I'd like to avoid, therefor the questions are, if anyone has a better solution/approach or some ideas how to reduce code or the need to change code with my idea?

Things I currently don't like on my idea but haven't found better solutions:
1. To much heap allocations (e.g `var intValidator`)

**Comment by asaskevich** [comment]
I also agree that it will be great to use something like `equal(value)`. Unfortunately, I haven't any better solution, you can ask @slugmobile for help, as he is author of validation of structs. I hope, that he can advice better solution as he fully knows  process of struct validation.

**Comment by Dadie** [comment]
Yay, it took me only... 2 Weeks (and a failed exam ._.'') but I somewhat made a prototype. I'll try to add more tests to the prototype in the next days.

https://github.com/Dadie/govalidatorcore
https://github.com/Dadie/govalidators

What the prototype changes: tags are now calls to validation methods. (So goodbye to the old look-up-map for functions). 

e.g.
```go
type Foo struct {
    bar string `valid:"ascii,ascii.Confirms(),ascii.upperCase(),ascii.equal(1234)"`
}
```
The prototype will now look for an validator with name "ascii". `ascii` and `ascii.Confirms()` is equal and checks just whether the ``Confirms()`` method of the "ascii"-validator returns TRUE or FALSE. Same is with ``ascii.upperCase()`` and ``ascii.equal(1234)``. The validatorcore looks up whether the "ascii"-validator has methods called "upperCase(value interface{})" and "equal(value interface{}, equaltostr string)" and applies the arguments to the methods.
(end of example)

Also the validators and the govalidator(core) are now separated entities. So my hope is we could have  stable validator packages and unstable validator packages. Maybe even versionize the packages like "govalidator_0_2_0_unstable".  

Anyway, this is only a prototype. This is not how the final commit would look like. The code isn't that nice structured, performance is really bad and I probably missed a lot of error checking :/ But it shows what my initial idea was (and goes even further)

**Comment by Dadie** [comment]
I've done a bit of trial and error in the design of the prototype and now the prototype is full modular. Currently there is only one validator package module (``govalidators``). But it could be split in for example ``govalidator_ascii`` , ``govalidator_integer`` , ``govalidator_string`` et cetera. This way, one would only need to import the needed validators.

As always, I'm happy for any kind of comment.

**Comment by asaskevich** [comment]
Sorry for delay, I very busy at last days -_- , I will review your work in the next weekend. Hope that all fine with your exams today.

**Comment by Dadie** [comment]
no problem ^^ I just rewrote a lot of the prototype anyway :P. The reason for the rewriting was "[reasoning](https://github.com/Dadie/govalidatorcore/blob/master/README.md#reasoning)" *Ba Dum Tish* . My next (feature) goal for the Prototype would be concurrency for validators. 

After that I would call the prototype "feature complete". The next step would then be optimizing (reduce memory usage, code, reflect usage, cpu usage).

**Comment by Dadie** [comment]
I shouldn't have sad it would then be "feature complete", now I'm having a lot of new ideas, e.g. how to handle Arrays and Structs! The Idea is to validate whether none, all or at least one value of an slice, array, map is valid.

Here an example:
```go
type Foobar struct {
	ints1     []int `valid:"EACH(integer.IsLess(10))"`
	ints2     []int `valid:"ANY(integer.IsLess(10))"`
	ints3     []int `valid:"NONE(integer.IsLess(10))"`
}
```

Also currently it is only possible to conjugate the Validators. So validating something like "i > 0 || i = -5" isn't currently possible! My Idea here would be introducing (similar to the EACH,ANY,NONE) the Keywords OR, AND, XOR, NOT. OR, AND, XOR should be able to use as Infix and prefix "operator". NOT would replace the !. (this would allow validators name to start with an !)

Here an example:
```go
type Foobar struct {
	orInfix   int   `valid:"integer.IsLess(10) OR integer.IsEqual(15)"`
	orprefix  int   `valid:"OR(integer.IsLess(10),integer.IsEqual(15))"`
	andInfix  int   `valid:"integer.IsLess(10) AND integer.IsEqual(15)"`
	andprefix int   `valid:"integer.IsLess(10) AND integer.IsEqual(15)"`
	xorInfix  int   `valid:"integer.IsLess(10) XOR integer.IsEqual(15)"`
	xorprefix int   `valid:"XOR(integer.IsLess(10),integer.IsEqual(15))"`
	complexer int   `valid:"(integer.IsLess(10) XOR integer.IsEqual(15)) AND NOT integer.IsEqual(0)"`
}
```

**Comment by nullboundary** [comment]
Hi slugmobile here (changed my username). 

Looks like some interesting work going on here, definitely like where this is going. However I would caution against adding too much tag validation logic. Since the validator is easily extendable anyway, if the tags are too specific it just adds unnecessary complexity. In this new version insuring a pattern for easily extending the validator should be emphasized as well. Personally in my own projects I am already doing many of these types of validation checks by adding my own validation functions to the tag map. This method does look more concise though and I would say the current tag map solution is getting a bit unwieldy and can't really go on extending forever so this looks promising. 

Your solution does make validation checks much more powerful, but I think its also important to remember whats is useful and what is too specific. So far its looking good, but this could easily evolve into its own validation tag mini language. Not to say that wouldn't be useful in some cases, but over all I think keeping the tags simple and effective should be a priority. At certain point its just easier and more maintainable to write a function in Go then to have a very complex tag validation string. Just something to keep in mind while designing the library. 

Also this definitely should go into its own branch. Its radically different from the current version, so this should probably be 2.0 or something. The current branch could be maintained for awhile and when this one is ready the project can move over to it. 

My 2cents.

**Comment by Dadie** [comment]
Thanks for comment @nullboundary, I'll keep that in mind. Keeping the validator simple, useful, powerful and *not overcomplex* is a goal I lost somewhere ._.'' . The current prototype has to much hassle (e.g Reasons, Errors, Results, Validators).

And yes, for a short time I even thought of using OCL as language with some extensions. I'm quite happy I didn't went that far. I already felt in my last comment, that the AND/OR/XOR/NOT syntax may creates quite long and maybe not good readable or understandable validations.

So again thanks for reminding me :)

Also the current prototype is planed to be 100% legacy-compatible. So I hope no one  will really notice the internal changes (and possible version jump).

**Comment by asaskevich** [comment]
Hi, as I see, there are a lot of work that already done. Great :smile: . `govalidatorcore` and `govalidators` looks cool. I think that your idea is much better than current implementation of my `govalidator`. Sorry for the long delay, I was really busy -_-

**Comment by Dadie** [comment]
no problem ^^ I'm one of this old "analog-dudes" that doesn't notoriously check mails, github and co. daily. So a "delay" of a few days is more or less not existing for me xD

Anyway, I also like the Idea but I'm currently not that happy about my (prototype) implementation. I don't know how to reduce the code even more  and simplify the system without sacrificing features ._.''

So currently I'm circling in my room,  thinking how to change the design. But I haven't found a better approach so far. Which also means I'm open for any kind of idea/approach/design :D

**Comment by nullboundary** [comment]
Hi, maybe I confused you. I didn't want to set you off track. I would say to don't worry about reducing code, but think more about how you use the library. The interface so to speak. If you are really not sure what to do next, maybe you can start with trying to make some of the current features compatible with your code. While doing that you might think of some better ways to proceed.

**Comment by Dadie** [comment]
You didn't set me off track, more or less you did the opposite. "Reducing code" maybe wasn't the best way to phrase it. The library should be as powerful as needed but as easy and clear to use as possible. Good code with few lines is often quite easy and clear (hence 'reducing code'). And I totally lost focus on that and just made an overengineered "Monster" which wasn't that easy to use and that clear. Currently the code is (IMO) much more useful and clear than the first initial design.

So yes, my current focus isn't about simply reducing the LoC but reducing every not needed overhead and making the API more clear and easy to use. I'll try doing what you say and will add more features of the current govalidator. 

Maybe this way I find some good ideas ^^

**Comment by manucorporat** [comment]
Hi, it's Manu. Creator and maintainer of the the Gin Framework.

"e have been having problems with our current validation library, and I am evaluating alternatives.
I wonder if this feature will be available soon.

**Comment by asaskevich** [comment]
Issue is out-of-date or very old, I closed it. So, if it necessary, you can create a new one or reopen this.

**Comment by rubenhazelaar** [comment]
Hopefully there are more people waiting for this feature. For me this one would be great. There is one for strings ("length(min|max)"; broken according to #93), however for me personally I would want to use it to limit integers.

**Comment by mwmahlberg** [comment]
@asaskevich Would there still be interest in a PR that implements `min([-]x[.y])` because I have a PR for this almost ready. However, it would be nice beforehand wether the rather excessive tests needed would be worth writing.
