### ISSUE TITLE
Custom Validators API

### ISSUE THREAD

**Issue by dlsniper** [asaskevich/govalidator#43]
Hi,

Thanks for the awesome work on the package.
I want to ask you if you'd be ok with me adding a custom validators option to the package so that other people could use the validators with this package without going to the same pains of doing the field tag reading and so on.
Thank you.

**Comment by dlsniper** [comment]
Nvm, I've read the docs again and found it.

**Comment by asaskevich** [comment]
Not a problem! If you had some questions, you can ask them :smile:
