### ISSUE TITLE
Urls with subdomain are not matching 

### ISSUE THREAD

**Issue by raul-brainattica** [asaskevich/govalidator#48]
IsURL validator is not working  with urls which contains subdomains. 
e.g The url "https://s3.amazonaws.com/bucket/5113a82b-06b6-418c-fd34/eae2b303-a7b2-4707-b04a" is not matching with IsURL method.

Any ideas? Maybe include this into URL string which contain url regular expression?

Thanks in advance.

**Comment by asaskevich** [comment]
Take a look to this issue: https://github.com/asaskevich/govalidator/issues/30
I think, they're similar.

**Comment by raul-brainattica** [comment]
Yeah! It´s working. Thanks a lot!

2015-03-07 10:22 GMT+01:00 Alex Saskevich <notifications@github.com>:

> Take a look to this issue: #30
> <https://github.com/asaskevich/govalidator/issues/30>
> I think, they're similar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asaskevich/govalidator/issues/48#issuecomment-77681012>
> .
>



-- 
Raúl.

**Comment by asaskevich** [comment]
Okey, I will review IsURL and make its behavior same to IsRequestURL
