### ISSUE TITLE
More Documentation / Need of Specification

### ISSUE THREAD

**Issue by Dadie** [asaskevich/govalidator#49]
Looking at issue #48, I think adding more documentation (not only in the code, but also on the README) and adding specification may helps to avoid misunderstandings on how a validation functions works/should work. A clear and good documentation and specification also may shows us cases that should be tested but currently are not. Or whether the current implementation is good or not.

The specification should be based on the idea of the validation functions and not on the current implementation. This may leads to changes in the current validation functions implementation and documentation but also leads to more reasonable and understandable validation functions. 

I tried to add [documentation](https://github.com/Dadie/govalidator/tree/documentation) using the information of how the validation functions works. But that only led me to some "inconsistent" behavior. E.g. in some "Is"-Numeric validation function leading zeros are valid, in some not. Sometime empty string is valid, sometimes not.

But these are not by any meaning bugs! The question is, what was the intention of the validation function (what is the specification).

**Comment by asaskevich** [comment]
I have no enough time to do better documentation :( I think that same functions should have same behavior, e.g. IsAlpha and IsUnicode should to return same answer for empty strings. I already looked at your updates with docs, it's awesome. It can be moved to govalidator after completing.

**Comment by asaskevich** [comment]
Issue is out-of-date or very old, I closed it. So, if it necessary, you can create a new one or reopen this.
