### ISSUE TITLE
validateStruct - handle on struct in validation

### ISSUE THREAD

**Issue by danjac** [asaskevich/govalidator#53]
This might be useful in a number of contexts, for example:

1. Comparing passwords/emails in a signup form
1. Checking unique email address in the database, where we want to exclude a user's current ID

I was thinking of something like the TagMap, e.g:
    
    govalidators.StructMap["passwordsEqual"] = govalidators.StructValidator(func(s interface{}, str string) bool {
        return str == i.(MyStruct).PasswordCheck
    })
  
These validators would then be run under ValidateStruct.

**Comment by asaskevich** [comment]
Please, check relevance of the issue with current version of the library. Issue is seems to be very old, I closed it. So, if it necessary, you can create a new one or reopen this. 😃
