### ISSUE TITLE
Validate other types like int, float etc

### ISSUE THREAD

**Issue by sebest** [asaskevich/govalidator#55]
Do you plan on supporting (or accepting patches) for other types than strings?

**Comment by asaskevich** [comment]
Yes, it works not only with strings, package already has basic support of structures validation. I think that package should to have various functions for validating integers, arrays, maps etc, like `func InRange(num, l, r int) bool` or anything like `func IsString(v interface{}) bool`. Also, it will not be superfluous, to have functions for working with arrays like `Any(f predicate), Filter(f predicate), Map, Count, All, etc` where `predicate` is `func (item interface{}) bool`.

It's just some features planned for the next releases. But if you have ideas or patches - you are welcome :smile:

**Comment by sebest** [comment]
Good to know!

thanx

**Comment by oryband** [comment]
@asaskevich maybe we should reopen this until this issue is fixed
I just wasted an hour not knowing that tagmap validation functions don't work on nested int types in structs.
