### ISSUE TITLE
URL regex returns false positive

### ISSUE THREAD

**Issue by OscarSwanros** [asaskevich/govalidator#62]
If you test the URL regex with a plain string as `foo` it returns true when it shouldn't as its not a valid URL.

**Comment by leadinglocally** [comment]
https://pbs.twimg.com/profile_images/560826135676588032/j8fWrmYY_normal.jpeg

This image URL is invalid according to this package

**Comment by nathj07** [comment]
I think this and #66 are the symptoms of the same thing. I'm looking into this now and hope to have a pull request on it soon

**Comment by asaskevich** [comment]
Fixed in #70
