### ISSUE TITLE
JSON style validation errors

### ISSUE THREAD

**Issue by wyattjoh** [asaskevich/govalidator#63]
It would be neat to have the errors returned as JSON instead of a string.

Given

```
type Profile struct {
  Email string `json:"email" valid:”required,email”`
}

type User struct {
  Profile Profile `json:"profile" valid:”…”`
}
```

you get errors back like

```
{
  “profile”: {
    “email”: [
      “non zero value required",
      "does not validate as email"
    ]
  }
}
```

**Comment by asaskevich** [comment]
Good idea, but at this moment I haven't thoughts how to solve it :smile: I will keep in mind this issue, maybe I'll find solution. Now you can do something using `ErrorByField` function, I hope that it will a bit helpful
