### ISSUE TITLE
Can't Validate Type Int

### ISSUE THREAD

**Issue by stilldavid** [asaskevich/govalidator#64]
It appears `int` is no longer a valid struct validator. I'm getting a message "Field: Validator int doesn't supported Kind int", which is strange.

You can reproduce by adding `,int` to line 1572 of `validator_test.go`.

I could be way off, too, let me know if you want a more proper test case or to dig in further.

**Comment by Dadie** [comment]
I somewhat expected this kind of issue in near future. At "fault" is the commit e743b6953f1e4f94e41310d96f1f353691383eaa

The thing is, so far "String" is the only Kind the current govalidator is able to validate. The only "validation" that works on every Kind is "required". All other "validations" currently only work on Kind "String".

Until e743b6953f1e4f94e41310d96f1f353691383eaa the validation of any non "String" Kind field was simply skipped. I thought skipping them wasn't a good design, as it might lead to thinking the current struct is valid even though I might no be.

Half-OT:
Currently I'm working on a "big Patch" that allows validation on any Kind. Current Prototype of the "big Patch" is[govalidatorcore](https://github.com/Dadie/govalidatorcore) with[govalidators](https://github.com/Dadie/govalidators). The prototype should be backward compatible, but as a prototype it might changes a lot over time.

**Comment by franklinkim** [comment]
:+1: any update on this one!? very interested in being able to validate other types than strings!

**Comment by asaskevich** [comment]
Please, take a look at #141, they are similar.
