### ISSUE TITLE
strange problem validating URLs

### ISSUE THREAD

**Issue by bolshoy** [asaskevich/govalidator#66]
http://www.example.com - OK
http://me.example.com - "http://me.example.com does not validate as url"
http://www.me.example.com - "http://www.me.example.com does not validate as url"

looks like there's a problem with subdomains which are different from www in the regexp...

**Comment by nathj07** [comment]
I actually have a pull request (just openned) that adds a few tests. I'll try to handle this issue in there. It shouldn't be too tricky.

**Comment by asaskevich** [comment]
Fixed in #70
