### ISSUE TITLE
Can't validate Wikipedia's URL

### ISSUE THREAD

**Issue by kfei** [asaskevich/govalidator#72]
Hi. Thanks for this awesome project!

I just notice that a home page URL of Wikipedia (which contains Unicode characters) can not pass the validation: `https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5`

**Comment by sivagollapalli** [comment]
@kfei I have just added test for Wikipedia URL. But test has been passed.

**Comment by asaskevich** [comment]
Yes, all works fine, here is test: https://github.com/asaskevich/govalidator/blob/master/validator_test.go#L621
I will close this issue, but if you find anything strange, let me know, please
