### ISSUE TITLE
Return slice of errors in ValidateStruct

### ISSUE THREAD

**Issue by olanod** [asaskevich/govalidator#85]
I think it makes more sense to return `[]error` from `govalidator.ValidateStruct` since a struct can have many errors and that should be represented as a collection of errors. And it also makes my life easier because one lib I'm using expects a slice of error

**Comment by chrisjones-brack3t** [comment]
I just ran into the same issue and agree that `[]error` should be returned rather than a concatenated string of errors. Maybe the better solution is to provide another `ValidateStruct` type function that returns `[]error`. Then you're not breaking anything.

**Comment by craigjackson** [comment]
The underlying data structure is `[]error`. However, `ValidateStruct` function signature just makes the return value be the `error` interface:

```go
	var errs Errors
	// ... folded code
	if len(errs) > 0 {
		err = errs
	}
	return result, err
```
https://github.com/asaskevich/govalidator/blob/1a4bf7e7a98e6a6484254ac41c52ef20ec30814e/validator.go#L499

The `Errors` type is `[]error`:

```go
type Errors []error
```
https://github.com/asaskevich/govalidator/blob/1a4bf7e7a98e6a6484254ac41c52ef20ec30814e/error.go#L3

I believe if someone changed the return types of function to `(bool, Errors)`, returned `nil` `if len(errs) == 0` and removed the variable `err` in the function and return errs instead, it would not be a breaking change.

**Comment by alioygur** [comment]
I don't agree with this.

You can get errors like this.
```go
_, err := govalidator.ValidateStruct(v)

if err != nil {
	errs := err.(govalidator.Errors)
}
```

**Comment by alioygur** [comment]
I think the ValidateStruct function should return only error.

if returned value not equal to nil, I will know that validation falied. otherwise I know it passed.

**Comment by asaskevich** [comment]
@alioygur but it will break BC with active projects. Maybe in future there will be something like validators, that returns errors and validators, that returns warnings etc. I closed it, but feel free to send pull request. 👍

**Comment by paulwalker** [comment]
What about adding a slice of field errors on the returned single error instance itself? What is the error type btw? Is there any metadata returned?
