### ISSUE TITLE
Validator int doesn't supported Kind int

### ISSUE THREAD

**Issue by Zevran** [asaskevich/govalidator#88]
Hello,

I recently updated your package and I am getting an strange issue !
I get this :
```
Limit: Validator int doesn't supported Kind int;
```
When I try to validate this struct :
```go
var Form struct {
	Offset int `valid:"int"`
	Limit  int `valid:"int"`
}
```
And If I remove Limit Validator the issue disappear.

Thanks !

**Comment by asaskevich** [comment]
Yes, currently it works with strings, but here is PL with supporting custom types, like int: https://github.com/asaskevich/govalidator/pull/91
Look on it, maybe it will be useful for your issue

**Comment by asaskevich** [comment]
#141
