### ISSUE TITLE
I want to know more about SafeFileName function.

### ISSUE THREAD

**Issue by phangji** [asaskevich/govalidator#95]
I want to look at the source of SafeFileName function.
but I cannot find the source in this repository.
and I tested the function in my go project. It's working.
by the way, the reason why i want to look into that function is that the function is too strict in my opinion.
What kind of rules that function followed? Can I have a reference of it?

**Comment by asaskevich** [comment]
Take a look here: https://github.com/asaskevich/govalidator/blob/master/utils.go#L154
